version: "2"
plugins:
engines:
  duplication:
    enabled: true
  fixme:
    enabled: true
  sonar-java:
    enabled: true
    config:
      tests_patterns:
        - src/test/**
exclude_patterns:
  - "target/"
