language: java
jdk:
- oraclejdk8
script: mvn test --quiet --batch-mode --settings .travis.settings.xml
after_success:
- mvn site site-deploy --quiet --batch-mode --settings .travis.settings.xml
- mvn clean test jacoco:report coveralls:report --batch-mode --settings .travis.settings.xml
cache:
  directories:
  - $HOME/.m2
env:
  global:
  - secure: r6l+3I+3OMfo4iSyLuioOE91OxUdoDUZ9WPW/kjdE9Hr//0SQAJcQwIGJPMLIPaOKB5uXFG/P8TaoX/m1vzCvwDM+cmPUjGGHbmQLenlGjeogCtZWWt3olzf4ljU9uRtrCPLsmqJIxCkE9XXQp45Eue7NvVfGvuVs8Dv8EbDBXZ+2NCTq9ybNHjOd7dhf9gdenggi93wH+MX+dKV1S4SRrlHSYTUpHortjrZKT95mliUKmpfZcpihbohonuotXZC+Gq8kIMQ+xJfFjkAiIz33XFT6HeSsdUOLbFnixMdGsvE4AoBheVYpZznVeFnIMnTKozRmgxUpVbMwuqZIR4LkidD3bUIdKWHRlxB6kayCaRdKjcbrNT2JCYV3SQN50YVlWRXufLMnxYei7kAEltzkwllzQwM7gU8G40SOhkF1sTVDeLD91kgehhNiGaSO6Z59HkGL6vb0TkSkIYkNCAaJlhYrVNUXA9I6IDKjRJKt91z4RW6qXE5fNvsmubKJmS2gz2XAEOTg2YOpLpb5oFM6bSvRKTia9NIBKHqQ4U6VrGeSdZ6+IRwnRYgIm95B8GxzQO/kkvR/3mzM1oObSjPcv/VniTQLeDII9qSpVRQV1UFvwHUsGylG9G3d3JgoXxv3dAkdB8r+qHP0tMG8O8/iMzTTXWyStPGhq0ndtCPxdM=
